# Generated by Django 4.1.3 on 2022-11-25 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homenagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_nasc', models.DateField()),
                ('cidade_nasc', models.CharField(max_length=50)),
                ('data_falec', models.DateField()),
                ('cidade_falec', models.CharField(max_length=50)),
                ('memoria', models.TextField(blank=True, max_length=255, null=True)),
                ('biografia', models.TextField(blank=True, max_length=800, null=True)),
                ('foto', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
