# Generated by Django 4.1.3 on 2022-12-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homenagem', '0002_alter_homenagem_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homenagem',
            name='biografia',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
